export const ADD_MESSAGE = "ADD_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_WITH_CHAT = "DELETE_MESSAGE_WITH_CHAT";
export const DELETE_CHAT = "DELETE_CHAT";
export const ADD_CHAT = "ADD_CHAT";